### ISSUE TITLE
ImportError: No module named hotmart_bot.__main__

### ISSUE THREAD

**Issue by diego-vieira** [danielmapar/HotimartBot#11]
```
~/Projects/HotimartBot master*
❯ poetry config virtualenvs.in-project true

~/Projects/HotimartBot master*
❯ poetry install
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 35 installs, 4 updates, 0 removals

  • Installing attrs (20.3.0)
  • Updating certifi (2020.11.8 -> 2020.12.5)
  • Updating chardet (3.0.4 -> 4.0.0)
  • Installing click (7.1.2)
  • Installing iniconfig (1.1.1)
  • Installing mccabe (0.6.1)
  • Installing mypy-extensions (0.4.3)
  • Installing packaging (20.8)
  • Installing pathspec (0.8.1)
  • Installing pluggy (0.13.1)
  • Installing py (1.10.0)
  • Installing pycodestyle (2.6.0)
  • Installing pyflakes (2.2.0)
  • Installing regex (2020.11.13)
  • Installing snowballstemmer (2.0.0)
  • Installing toml (0.10.2)
  • Installing typed-ast (1.4.2)
  • Installing typing-extensions (3.7.4.3)
  • Updating urllib3 (1.25.11 -> 1.26.2)
  • Installing black (20.8b1)
  • Installing configparser (5.0.1)
  • Installing coverage (5.3.1)
  • Installing crayons (0.4.0)
  • Installing flake8 (3.8.4)
  • Installing pydocstyle (5.1.1)
  • Installing pytest (6.2.1)
  • Updating requests (2.24.0 -> 2.25.1)
  • Installing flake8-annotations (2.5.0)
  • Installing flake8-black (0.2.1)
  • Installing flake8-docstrings (1.5.0)
  • Installing flake8-import-order (0.18.1)
  • Installing mypy (0.790)
  • Installing pathvalidate (2.3.2)
  • Installing pycryptodome (3.9.9)
  • Installing pytest-cov (2.11.0)
  • Installing python-dotenv (0.15.0)
  • Installing selenium-wire (2.1.2)
  • Installing webdriver-manager (3.2.2)
  • Installing youtube-dl (2020.12.31)

Installing the current project: hotmart-bot (0.1.0)

~/Projects/HotimartBot master* 1m 26s
❯ poetry run hotmart-bot https://COURSE.club.hotmart.com email password
Skipping virtualenv creation, as specified in config file.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named hotmart_bot.__main__
```

**Comment by mpupo** [comment]
Can you provide more evidence? 

I downloaded a new copy inside my machine, and it worked well (evidence below).

```bash
Murilo@DESKTOP-MURILO-PC MINGW64 /i/PupoDev
$ git clone https://github.com/danielmapar/HotimartBot.git
Cloning into 'HotimartBot'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (45/45), done.
Reremote: Total 76 (delta 20), reused 42 (delta 9), pack-reused 13
Receiving objects: 100% (76/76), 412.61 KiB | 910.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.

Murilo@DESKTOP-MURILO-PC MINGW64 /i/PupoDev
$ cd HotimartBot

Murilo@DESKTOP-MURILO-PC MINGW64 /i/PupoDev/HotimartBot (master)
$ poetry install --no-dev
Creating virtualenv hotmart-bot in I:\PupoDev\HotimartBot\.venv
Installing dependencies from lock file


Package operations: 15 installs, 0 updates, 0 removals

  - Installing certifi (2020.12.5)
  - Installing chardet (4.0.0)
  - Installing colorama (0.4.4)
  - Installing idna (2.10)
  - Installing urllib3 (1.26.2)
  - Installing configparser (5.0.1)
  - Installing crayons (0.4.0)
  - Installing requests (2.25.1)
  - Installing selenium (3.141.0)
  - Installing pathvalidate (2.3.2)
  - Installing pycryptodome (3.9.9)
  - Installing python-dotenv (0.15.0)
  - Installing selenium-wire (2.1.2)
  - Installing webdriver-manager (3.2.2)
  - Installing youtube-dl (2020.12.31)
  - Installing hotmart-bot (0.1.0)

Murilo@DESKTOP-MURILO-PC MINGW64 /i/PupoDev/HotimartBot (master)
$ poetry run hotmart-bot -usr TEST -pwd PASS https://google.com
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [C:\Users\Murilo\.wdm\drivers\chromedriver\win32\88.0.4324.96\chomedriver.exe] found in cache
Error making request
Traceback (most recent call last):
  File "I:\PupoDev\HotimartBot\.venv\lib\site-packages\seleniumwire\proxy\proxy.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 944, in send
    self.connect()
  File "I:\PupoDev\HotimartBot\.venv\lib\site-packages\seleniumwire\proxy\proxy.py", line 368, in connect
    super().connect()
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 1392, in connect
    super().connect()
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\http\client.y", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\socket.py", ine 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\socket.py", ine 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "i:\pupodev\hotimartbot\src\hotmart_bot\__main__.py", line 40, in main
    hb.login(SITE, USERNAME, PWD)
  File "i:\pupodev\hotimartbot\src\hotmart_bot\bot\hotmart_bot.py", line 68, inlogin
    login.clear()
AttributeError: 'NoneType' object has no attribute 'clear'
```
OBS: I used `poetry install --no-dev` only to speed up the install process. This AttributeError is because I canceled the execution.

**Comment by mpupo** [comment]
@diego-vieira Can you post here your Poetry config? You only need to run `poetry config --list`on your terminal. 

Maybe this error is caused by the path inside the .toml file on the root of repository. I never experienced that error with Poetry, but it will be fun (and useful) to solve it.

**Comment by mpupo** [comment]
I worked around the feature of creating virtual environments outside the project folder via Poetry ( with `poetry  config virtualenvs.in-project false --local` and it worked as expected. See the output of my console below:

```
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡█ 3.8.2█ poetry config virtualenvs.in-project false --local
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ poetry install 
Creating virtualenv hotmart-bot-qjINM0CO-py3.8 in C:\Users\Murilo\AppData\Local\pypoetry\Cache\virtualenvs
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` 
command.
Installing dependencies from lock file


Package operations: 45 installs, 0 updates, 0 removals

  - Installing typing-extensions (3.7.4.3)
  - ....

█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ poetry run hotmart-bot -usr test@test.com 
-pwd 12345 https://cursounderchef.club.hotmart.com/login
 
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - There is no [win32] chromedriver for browser 89.0.4389 in cache
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_win32.zip
[WDM] - Driver has been saved in cache [C:\Users\Murilo\.wdm\drivers\chromedriver\win32\89.0.4389.23]
```

Reading the first comment of this issue, I found something curious: 
```
~/Projects/HotimartBot master*
❯ poetry config virtualenvs.in-project true

~/Projects/HotimartBot master*
❯ poetry install
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file
```

I replicated this and it worked normally, even if this has updated many packages in my system-wide python library:
```
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ poetry config virtualenvs.in-project true 
--local
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ poetry config virtualenvs.create false --local
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ poetry install
Skipping virtualenv creation, as specified in config file.
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` 
command.
Installing dependencies from lock file


Package operations: 22 installs, 22 updates, 0 removals

  - Installing typing-extensions (3.7.4.3)
  - Updating pyparsing (2.4.7 C:\Users\Murilo\AppData\Local\Programs\Python\Python38\lib\site-packages -> 2.4.7)
  - ....

█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ poetry run hotmart-bot -usr test@test.com 
-pwd 12345 https://cursounderchef.club.hotmart.com/login
Skipping virtualenv creation, as specified in config file.
 
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Driver [C:\Users\Murilo\.wdm\drivers\chromedriver\win32\89.0.4389.23\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:57023/devtools/browser/247f7cf8-9328-414c-8717-0e6302d1bd29
```

Then, I looked again at the first comment and I tested another thing: the python version that appeared in the console was the 2.7: 
```
❯ poetry run hotmart-bot https://COURSE.club.hotmart.com email password
Skipping virtualenv creation, as specified in config file.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named hotmart_bot.__main__
```

So, I installed the pyenv, configured the local python version to 2.7.18 (the latest one) and tried to install the project config:
```
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?1█ 3.8.2█ pyenv local 2.7.18
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?2█ █ poetry install
The currently activated Python version 2.7.18 is not supported by the project (^3.7).
Trying to find and use a compatible version.

[NoCompatiblePythonVersionFound]
Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```

I reverted all the configurations and I tried exactly the command that you had run:
```
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?2█ █ pyenv local 3.8.2
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?2█ 3.8.2█ poetry install
Creating virtualenv hotmart-bot in I:\PupoDev\HotimartBot\.venv
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` command.
Installing dependencies from lock file


Package operations: 45 installs, 0 updates, 0 removals

  - Installing typing-extensions (3.7.4.3)
  - ...

█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?2█ 3.8.2█ poetry run hotmart-bot https://COURSE.club.hotmart.com email password
usage: hotmart-bot [-h] [-usr USERNAME] [-pwd PASSWORD] [-ef] [-o OUTPUT_PATH] site
hotmart-bot: error: unrecognized arguments: email password
█Murilo@DESKTOP-MURILO-PC██I:\PupoDev\HotimartBot██master ≡  ?2█ 3.8.2█ poetry run hotmart-bot https://COURSE.club.hotmart.com -usr email -pwd password

[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Driver [C:\Users\Murilo\.wdm\drivers\chromedriver\win32\89.0.4389.23\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:57311/devtools/browser/7ad1f7c7-354a-4c65-9312-c71ce58b0249
```

Can you try to run with poetry config like below?
```
poetry config virtualenvs.in-project true --local
poetry config virtualenvs.create true --local
poetry run hotmart-bot -usr test@test.com -pwd 12345 https://course..club.hotmart.com
```

Do not forget to use a supported python version (^3.8).
