### ISSUE TITLE
Don't work with current site

### ISSUE THREAD

**Issue by obtim** [danielmapar/HotimartBot#17]
Use Python 3.8 on Windows 7 with PowerShell 3.0 
Cant download https://futebolparainvestidoresacessop.club.hotmart.com/
Tried
PS D:\hotmartbot\src> python -m hotmart-bot -usr xxx@xxx.com -pwd xxx futebolparainvestidoresacesso
p

[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Driver [C:\Users\1\.wdm\drivers\chromedriver\win32\89.0.4389.23\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:4133/devtools/browser/88c8af0b-05a6-4e1c-aa0a-b2c26c482d1e
[8120:7264:0405/165624.058:ERROR:device_event_log_impl.cc(214)] [16:56:24.058] USB: usb_service_win.cc:258 Failed to get
 device driver name: ▌ыхьхэЄ эх эрщфхэ. (0x490)
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\hotmart-bot\__main__.py", line 58, in <module>
    main()
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\hotmart-bot\__main__.py", line 50, in main
    module.lessons = hb.get_lessons_list(module)
  File "D:\hotmartbot\src\hotmart_bot\bot\hotmart_bot.py", line 116, in get_lessons_list
    for video in self._extract_video_urls():
  File "D:\hotmartbot\src\hotmart_bot\bot\hotmart_bot.py", line 60, in _extract_video_urls
    cookies = self.get_cookies(src)
  File "D:\hotmartbot\src\hotmart_bot\bot\hotmart_bot.py", line 156, in get_cookies
    match = video_id_regex.match(video_url)
TypeError: expected string or bytes-like object

In Chrome browser(WebDrive) I saw "connection is lost" in media windows. But everything was fine in normal browser

**Comment by kgdkp** [comment]
I have the same problem

I've tried to correct, but to no avail
