### ISSUE TITLE
Error in midnigth theme

### ISSUE THREAD

**Issue by leofera257** [danielmapar/HotimartBot#19]
Cant download course in midnight theme

poetry run hotmart-bot -usr xxxxxx -pwd xxxxxxx oftr3vi3w3xt3nsiv3

[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Driver [C:\Users\xxxx\.wdm\drivers\chromedriver\win32\89.0.4389.23\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:51331/devtools/browser/b9356fa6-35c2-4a17-9ebe-ccb188c3182b
[6940:7712:0407/180240.385:ERROR:device_event_log_impl.cc(214)] [18:02:40.384] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Um dispositivo conectado ao sistema nπo estß funcionando. (0x1F)
[6940:7712:0407/180240.386:ERROR:device_event_log_impl.cc(214)] [18:02:40.386] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Um dispositivo conectado ao sistema nπo estß funcionando. (0x1F)
[6940:7712:0407/180240.386:ERROR:device_event_log_impl.cc(214)] [18:02:40.386] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Um dispositivo conectado ao sistema nπo estß funcionando. (0x1F)
[6940:7712:0407/180240.392:ERROR:device_event_log_impl.cc(214)] [18:02:40.392] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Um dispositivo conectado ao sistema nπo estß funcionando. (0x1F)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\HotimartBot-master\src\hotmart_bot\__main__.py", line 41, in main
    modules = hb.get_modules_list()
  File "C:\HotimartBot-master\src\hotmart_bot\bot\hotmart_bot.py", line 80, in get_modules_list
    modules_elements = self._driver.find_element_by_id(
  File "C:\HotimartBot-master\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\HotimartBot-master\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\HotimartBot-master\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\HotimartBot-master\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="navigation-modules"]"}
  (Session info: chrome=89.0.4389.114)

**Comment by lucassmacedo** [comment]
i have the same problem.

**Comment by mpupo** [comment]
Hi @leofera257  and @lucassmacedo!

Can you save the midnight HTML page with at least showing 1 module and 1 lesson list and upload it somewhere? 

Thanks for the collaboration!

**Comment by lucassmacedo** [comment]
Hello @mpupo. 
https://paste.ee/p/14E6E
If you need someting else tell me. 
Thanks
