### ISSUE TITLE
Not downloading VIMEO videos - Missing Cookies

### ISSUE THREAD

**Issue by fequintas** [danielmapar/HotimartBot#24]
Hello,

I've run the python project and everything worked until reached the first video.
The code was able to walk through the page and on each module/class.
When it get in on the first class with video content, chrome complain about the cookies and the run fails:

PS C:\Users\USUARIO\OneDrive\Documents\HotimartBot-master\HotimartBot-master> poetry run hotmart-bot -usr user@user.com -pwd xxxxxxx curso-vr-rx

[WDM] - Current google-chrome version is 107.0.5304
[WDM] - Get LATEST driver version for 107.0.5304
[WDM] - Driver [C:\Users\USUARIO\.wdm\drivers\chromedriver\win32\107.0.5304.62\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:64444/devtools/browser/b79bf27e-42ca-40b5-af96-8d43b56b818e
[23820:20084:1101/101157.941:ERROR:util.cc(129)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USUARIO\OneDrive\Documents\HotimartBot-master\HotimartBot-master\src\hotmart_bot\__main__.py", line 50, in main
    module.lessons = hb.get_lessons_list(module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\OneDrive\Documents\HotimartBot-master\HotimartBot-master\src\hotmart_bot\bot\hotmart_bot.py", line 116, in get_lessons_list
    for video in self._extract_video_urls():
  File "C:\Users\USUARIO\OneDrive\Documents\HotimartBot-master\HotimartBot-master\src\hotmart_bot\bot\hotmart_bot.py", line 57, in _extract_video_urls
    yield Video("vimeo", src)
          ^^^^^^^^^^^^^^^^^^^
TypeError: Video.__init__() missing 1 required positional argument: 'cookies'
PS C:\Users\USUARIO\OneDrive\Documents\HotimartBot-master\HotimartBot-master> [24240:21636:1101/101258.164:ERROR:gpu_init.cc(537)] Passthrough is not supported, GL is disabled, ANGLE is

 
![Captura de tela 2022-11-01 101415](https://user-images.githubusercontent.com/117179231/199241737-b8ace84a-2756-4b91-a7e7-ccf47dbdccc5.png)

**Comment by EdesonABizerril** [comment]
I have this problem
